name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Check for secrets
        run: |
          pip install --no-cache-dir trufflehog
          trufflehog filesystem --no-update --fail .
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -e .[test]
      - name: Run tests
        run: |
          pytest -q
      - name: Build Docker CPU image
        run: |
          docker build -f docker/Dockerfile.cpu -t fm-playground:cpu .
